# Generated by Django 5.2.7 on 2025-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta_Admin', '0006_category_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
