# Generated by Django 5.2.7 on 2025-12-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta_Admin', '0007_subtask_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20, verbose_name='Статус подзадачи'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Meta_Admin.task', verbose_name='Главная задача'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название подзадачи'),
        ),
    ]
